### Make a story
POST http://localhost:8080/api/stories
Content-Type: application/json

{
  "title": "The Dark Forest",
  "genres": ["FANTASY", "ADVENTURE"],
  "tags": ["forest", "magic"],
  "maturityLevel": "TEEN",
  "writingStyles": ["DARK", "DRAMATIC"],
  "generalSetting": "A mysterious forest filled with ancient magic."
}

### Player action 1
POST http://localhost:8080/api/stories/story-1/actions
Content-Type: application/json

{
  "action": "Vejdu do lesa."
}

### Player action 1
POST http://localhost:8080/api/stories/story-1/actions
Content-Type: application/json

{
  "action": "Rozhlédnu se kolem sebe."
}

### Player action history
GET http://localhost:8080/api/stories/story-1