ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.myaiadventure.HttpKt.configureHttp
      - com.example.myaiadventure.SerializationKt.configureSerialization
      - com.example.myaiadventure.RoutingKt.configureRouting
